### ISSUE TITLE
Operator @-> can be used in make_model without error but doesn't add a rv.

### ISSUE THREAD

**Issue by MerlinHeidemanns** [integrated-inferences/CausalQueries#122]
@-> can be used in the statement but are ignored afterwards without causing an error.
If used alone they cause a "No root nodes provided error."
make_model("Z -> X @-> Y") # does not error but ignores Y
make_model("Z @-> X") # errors

I am uncertain whether this behavior is desired.

**Comment by macartan** [comment]
It looks like ("Z -> X @-> Y") is interpreted as ("Z -> X")
Why would you include @ in the model statement?  
Statements are used by dagitty, perhaps add a general check to make sure only permissible expressions are used

**Comment by MerlinHeidemanns** [comment]
@-> is permissible syntax in dagitty (dagitty users may think that this also works here) and not flagged so having a function check for permissible gbiqq input is probably good.

**Comment by macartan** [comment]
or better might be to allow any dagitty input but just retain the elements
we can work with
