### ISSUE TITLE
Error message in make_priors_single

### ISSUE THREAD

**Issue by MerlinHeidemanns** [integrated-inferences/CausalQueries#136]
Seems like the wrong/undesired output of make_priors_single
_Code_
make_model("X -> Y") %>% make_priors(statement = "X == 1", alphas = c(2, 0.5, 1, 3, 4, 5))
_Error_
Trying to replace  6  parameters with  6 values

**Comment by till-tietz** [comment]
make_par_values now produces the correct error 

```
Error in make_par_values(model = model, alter = "priors", x = alphas, :
Trying to replace 1 parameter(s) with 6 values.You either specified a wrong number of values or your conditions do not match the expected number of model parameters.
```
