### ISSUE TITLE
Error message ordering in make_priors_single

### ISSUE THREAD

**Issue by MerlinHeidemanns** [integrated-inferences/CausalQueries#137]
_Code_
model <- make_model("X -> M -> Y")
make_priors(model,
						distribution = c("certainty", "certainty", "jeffreys"),
						node = c("X", "M", "Y", "Z"))
_Output_
Provided arguments of length >1 should be of the same length
_Issue_
Unequal length is not the primary problem here given that Z is not in the model.
_Fix_
Check input nodes first?

**Comment by macartan** [comment]
the first issue is that distributionand node are of incompatible length. If you fix that then you run into the Z issue. OK to close?

> make_priors(model,
+ 						distribution = c("certainty", "certainty", "jeffreys", "certainty"),
+ 						node = c("X", "M", "Y", "Z"))
 Error in make_par_values(model, y = y, x = x, distribution = distribution,  : 
  listed nodes must be nodes in the model

**Comment by lilymedina** [comment]
I agreed on that is perhaps better to check input nodes first

Feel free to close issue if order of checks is not relevant.
