### ISSUE TITLE
restrictions issue / sequencing

### ISSUE THREAD

**Issue by macartan** [integrated-inferences/CausalQueries#202]
If restriction is imposed after prior / posterior set the prior / posterior distributions are incompatible; same with confounding
better to remove these distributions in such cases
```
model <- make_model("X -> Y") %>% set_prior_distribution

model <- set_restrictions(model, decreasing("X", "Y"))

query_distribution(model, query = "Y==1", given = "X==0", using = "priors")
```

**Comment by till-tietz** [comment]
@macartan @integrated-inferences what is the status on this issue?

**Comment by macartan** [comment]
resolved
