### ISSUE TITLE
bug counting causal types

### ISSUE THREAD

**Issue by macartan** [integrated-inferences/CausalQueries#209]
chain_model_restricted = make_model("X -> M -> Y") %>% 
  set_restrictions("M[X=1] < M[X=0]") %>%
  set_restrictions("(Y[M=1] < Y[M=0])")
  
 get_query_types(chain_model_restricted, "(X == 1 & Y == 1) & (Y[X=1]>Y[X=0])")

gives

X1.M01.Y01  
 Number of causal types that meet condition(s) =  2

the solution is correct but count should be 1 not 2

**Comment by till-tietz** [comment]
fixed

Issue was related to an edge case for queries matching an odd number causal types produced by the mechanics of printing causal types out in rows of two. As causal types get printed in rows of two, a "" was added to causal type vectors of odd length causing a count of +1 when length(types) was called for the 'Number of causal types that meet condition(s)' print out.
