### ISSUE TITLE
set_parameter_matrix possible issue

### ISSUE THREAD

**Issue by cristian-nicolescu** [integrated-inferences/CausalQueries#252]
is it intended that set_parameter_matrix works like this:
1. P_new <- get_parameter_matrix(model)
2. modify P_new as desired
3. model <- set_parameter_matrix(model, P_new) ?
If yes, it does not seem to work, there comes a message like "parameter_matrix already exists, no action taken"
Needed to assign it manually:
model[["P"]] <- P_new

**Comment by macartan** [comment]
here's a MWE:

```
model <- make_model('X -> Y')
P <- diag(8)
colnames(P) <- rownames(model$causal_types)
model <- set_parameter_matrix(model, P = P)
model <- set_parameter_matrix(model, P = P)

Parameter matrix already contained in model; no action taken
``` 

this is little used functionality but still we should allow P to be overwritten if an alternative is provided

**Comment by till-tietz** [comment]
Is this already implemented or do you want me to make the change for the upcoming CRAN release?

**Comment by integrated-inferences** [comment]
lets do this; should be straightforward

**Comment by till-tietz** [comment]
Nice; will implement this

**Comment by till-tietz** [comment]
Implemented on new branch, merging pull request will resolve the issue
