### ISSUE TITLE
Defining parameters bug?

### ISSUE THREAD

**Issue by cristian-nicolescu** [integrated-inferences/CausalQueries#254]
model <- make_model("R -> S -> F <- R; S <- U -> F") |> 
  set_restrictions("(F[S=0] == 1)") |>  
  set_restrictions("(S[R=0] > Stop[R=1])") 
# Set some parameters
 model <- model|>
   set_parameters(
     param_type = define,
     node = ",
     nodal_type = c("0001", "0101", "0111", "1111"),
     parameters = c(.3, 0.1, 0.05, 0.2 )
   )
   # Now try the same but when nodal types do not correspond to order in parameter vector
   model <- model |>
   set_parameters(
     param_type = define,
     node = ",
     nodal_type = c("1111", "0111", "0101", "0001"),
     parameters = c(0.2, 0.05,  0.1, 0.3)
   )
   
   The second does version seems to mix up the nodes, so the wrong parameters get assigned

**Comment by till-tietz** [comment]
@cristian-nicolescu @macartan this bug either arises in make_par_values or it's a simple cases of messed up assignment of the make_par_values -> make_parameters  output in set_parameters itself

**Comment by integrated-inferences** [comment]
here's a simpler example:

```
make_model("X -> Y") |>
  set_parameters(nodal_type = c("11", "00"), parameters = c(0, .5)) |>
  get_parameters()
```

I think it's just how the function works; it selects the type that satisfy the nodal_type list---without taking account of order---and assigns values accordingly.

Note it does this within nodes and not across nodes:
```
make_model("X -> Y") |>
  set_parameters(nodal_type = c("00", "11", "0", "1"), parameters = c(0, 1, .5, .5)) |>
  get_parameters()
```
we could provide a warning if nodes are provided out of order

**Comment by till-tietz** [comment]
Sounds like a good solution. I'll put together an implementation on a new branch.

**Comment by till-tietz** [comment]
Quick question: is the use case here to alter parameters for the specified types on all nodes?

**Comment by macartan** [comment]
It is possible with this function to change all instances of "01" for
instance, on multiple nodes; but that is not the main purpose; and actually
it's probably safer to specify a node, or group of nodes, when you do
this.  This is currently what `labels` does so there is some redundancy
there.

The most common use case though is to specify say node = Y, nodal_type =
c(01, 10) and then parameters;

The only issue is whether the parameters have to be listed in the order of
the provided nodal_types or in the order of the nodal_types in the
parameters df

**Comment by till-tietz** [comment]
I just went through the code I wrote on the make_par_values front. That's essentially where the 'problem' arises. Since we added all this functionality around different ways to specify where to alter parameters/priors make_par_values handles this by transforming all those different specifications into a logical vector of where to alter. This forces the update in order of parameters df (as you mentioned). 

I think there are three options here: 

1. throw a warning and just keep the updating procedure as is
2. throw an error and force the user to respecify 
3. do some surgery on make_par_values and put things in the correct order internally + print a message to that effect to console

**Comment by macartan** [comment]
I think if 3 is easy enough and does not slow things we shold do that;
otherwise 2; but not 1

**Comment by till-tietz** [comment]
I'll have a go at option 3. Shouldn't be too hard.

**Comment by integrated-inferences** [comment]
Perhaps prep the labels and parameters as a dataset and  left join

**Comment by till-tietz** [comment]
Found a way to sort out this problem. Currently writing up an implementation.

**Comment by till-tietz** [comment]
This issue should be solved now

set_parameters no respects the order specified by the user. 

## Quick overview of the internal working of parameters updating: 

`make_par_values()` does the bulk of the work. Based on the arguments provided alter_at, node, nodal_type, param_set, given, statement, param_names we construct filter commands executed with eval() that indicate which rows of parameters_df to change. 

* alter_at >> simply a fully formed filter statement 
* node, nodal_type, param_set, given, param_names >> obviously just columns in parameters_df 
* statement >> generates nodes and nodal_types to alter that can be combined with param_set and given  

## original method 

when specifying e.g.:

```
make_model("X -> Y") |> set_parameters(node = "Y", nodal_type = c("11", "00"), parameters = c(0, .5)) 
```

make_par_values() internally constructed the filter command: 

```
command <-  "node == 'Y' & nodal_type %in% c('11','00')" 
```

This would get turned into a logical vector of vector positions to alter with: 

```
to_alter <- with(model$parameters_df, eval(parse(text = command)))
```

This would force changes to parameters in the order parameters occur in parameters_df 

## new method 

We now utilize expand.grid to generate all combinations of specified arguments in effect generating separate filter commands for each parameter. i.e. for the above example: 

```
"node == 'Y' & nodal_type == '11'"
"node == 'Y' & nodal_type == '00'"
```

This then allows us to change the order of specified values to order of parameters in parameters_df

```
 # reorder new parameter values according to the parameter order in parameters_df
    param_df <- model$parameters_df
    names <- sapply(commands, function(i) {
      eval(parse(text = paste("param_df[", i, ",][['param_names']]")))
    })

    names(x) <- names
    x <- x[param_df$param_names]
    to_alter <- !is.na(x)
    x <- x[to_alter]
```

**Comment by till-tietz** [comment]
Tested the new functionality with the above example and some others and it appears to be working correctly. As long as the new function still lives on the `set_parameters_bug` branch you can test it locally by downloading CausalQueries from: 

```
devtools::install_github("integrated-inferences/CausalQueries", ref = "set_parameters_bug")
```

**Comment by integrated-inferences** [comment]
This is failing checks. 
e.g.
`    out <- CausalQueries:::make_par_values(model = model, x = c(0.5,0.25), param_names = c("X.0","X.1"))
    expect_equal(out, c(0.5,0.25,1,1,1,1))
`
weird line here at 219:
param_names <- c("Y.10_X.0","Y.10_X.1")


this also fails:
    out <- CausalQueries:::make_par_values(model = model, x = c(0.5,0.25), statement = "Y[X=1] > Y[X=0]")


and this:

	  out <- set_priors(model = model, alphas = c(0.5,0.25), statement = "Y[X=1] > Y[X=0]")

**Comment by till-tietz** [comment]
Update is stable and all tests are passing.
