### ISSUE TITLE
realise_outcomes node option when node has multiple parents

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#257]
Using the 'node' option in realise_outcomes without specifying 'dos' for all parents produces undefined behavior. I've added a safeguard for this case: the realise_outcomes implementation on 'main' now throws an error in these cases. 

- what is the intended use case for the 'node' option? Should we allow for 'dos' specification for a subset of parents? 
- as far as I'm aware the 'node' option is just a user facing convenience which we don't use in the guts of the package

**Comment by macartan** [comment]
Thanks Till --

I cannot find instances where the node argument is actually used. You could
certainly imagine it being useful for a user trying to understand how
particular outcomes are generated;

e.g. the output is so much more compact for this:
 model <- make_model("X->M->Y")
 realise_outcomes(model, dos = list(X = 1), node = "M")

than for this
 model <- make_model("X->M->Y")
 realise_outcomes(model, dos = list(X = 1))

and so you can explore a shortened model for example; however I don;t think
it is currently used e.g. in querying

the documentation currently says that all parents should be specified so I
think an error is fine and functional.

However if easy,  a nicer behavior would be to fix any specified parents
and have all combinations of unspecified parents with output like this.


 model <- make_model("X->M->Y")

> realise_outcomes(model, dos = list(X = .), node = "M")

   X M

00 0 0

10 0 1

01 0 0

11 0 1

00 1 0

10 1 0

01 1 1

11 1 1


If not easy then let's leave this as a future issue.

**Comment by till-tietz** [comment]
@macartan just pushed a fix to the `realise_outcomes_fix` branch that should should work. Let me know what you think

**Comment by macartan** [comment]
Hi Till -- reviewing I think I see three things:

1. This produces an error but it shouldn't:
make_model("X -> M -> Y") |>
  realise_outcomes(node = "Y")

Error in realise_outcomes(make_model("X -> M -> Y"), node = "Y") :
  Do actions must be specified when node is not NULL


2. This has 64 rows but it should only have 32
make_model("X -> Y <- Z") |>
     realise_outcomes(node = "Y", dos = list(X = 1))

These are duplicates:

         X Z Y
0.0.0000 1 0 0
1.0.0000 1 0 0


3
Something wacky happening here with restrictions:

> make_model("X -> M -> Y") |> set_restrictions("M[X=1]==1") |>+   realise_outcomes(node = "Y", dos = list(X = 1))        X  M  Y
0.00.00 1 00 00
1.00.00 1 00 00


4
note this works ok:
make_model("X -> M -> Y") |> set_restrictions("M[]==1") |>
  realise_outcomes()

**Comment by till-tietz** [comment]
Hi @macartan ;

thanks for flagging.

1. is an easy fix as this is just a remnant check from the previous version which I wasn't sure whether to deprecate 
2. This is due to how we construct the causal type data.frame when node is specified --> traverse_dag() moves backwards through the DAG from the specified node until it hits a root or a do. Then we expand.grid the nodal_types of the nodes this process returns. Should we additionally drop duplicate rows from the resulting data.frame?
3. Will investigate what happens there

**Comment by macartan** [comment]
on 2 --- I think we are seeing the goal here slightly differently. I think
I am imagining something simpler:

we only move back to the parents; we don;t have to go beyond the parents

so if we had A -> B -> C ->D , we only have to give the outcomes for D for
the D types and the two possible values for C: 4 four rows
similarly so if we had A -> C; B -> C ->D , we only have to give the
outcomes for D for the D types and the two possible values for C: 4 four
rows

if we have
 A -> B -> D <- C

we have 4 * 16 rows if no dos are satisfied, A is irrelevant and we just
take the 4 values of B and D (times 16 D types)
if one do is specified , then 2 * 16
of two dos  specified then just 16

I think we then just pass the parents dataset as realized data to the c
function?

there is a possibility that we evaluate here for some values of parents
that will never be realized; but I think it's ok since they could be
realised in principle via a do operation...

(note the current all_data_types / possible_data uses realise_outcomes!)

what do you think?

**Comment by till-tietz** [comment]
Let me just make sure I'm understanding correctly: 

Let's say we have "X1 -> M -> Y; X2 -> Y -> Z" with an intervention on "M" via do(M = 1). 
We want realised outcomes with node = "Y". The relevant sub DAG is "M -> Y <- X2" here. 

Currently realise_outcomes would return a data.frame of 128 rows when it actually should return 32 right?

**Comment by macartan** [comment]
Yes 32 rows
16*1*2

**Comment by till-tietz** [comment]
Here's what I'm thinking and correct me if I'm misunderstanding you: 

1. We work backwards through the DAG from the specified node until we hit a do or a root.
2.  We get the nodal types of all nodes in the sub DAG and replace types on nodes with interventions with the appropriate value (e.g. in the above M would only have type 1). 
3. We expand.grid that list of nodal_types (we can call drop duplicates here to make extra sure everything is in order) 
4. function proceeds as usual

**Comment by till-tietz** [comment]
Re-reading your comment above: are you suggesting we just treat the parents of a node as exogenous i.e. we just give them types "0" "1" (unless there is a do)?

**Comment by macartan** [comment]
Yes!
Seems simpler to me to just start off with the 0 and 1s for all parents,
reduce to 0 OR 1 when there's a do, and then calculate Y for each remaining
combination of parents using the c function.  So no need for moving through
the dag

**Comment by till-tietz** [comment]
Yeah that's much simpler. Easy fix; will get right on it and also check what's going on when setting restriction.
