### ISSUE TITLE
updating with censored_types CRAN 

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#259]
CRAN runs into the following error when updating and querying models with censored_types

make_model("X->Y") %>%
   update_model(data.frame(X=c(1,1), Y=c(1,1)), censored_types = c("X1Y0")) %>%
   query_model(te("X", "Y"), using = "posteriors")

_Chain 1: Initialization between (-2, 2) failed after 100 attempts.
Chain 1:  Try specifying initial values, reducing ranges of constrained
values, or reparameterizing the model.
[1] "Error : Initialization failed."
error occurred during calling the sampler; sampling not done
Stan model 'simplexes' does not contain samples.
Error in `colnames<-`(`tmp`, value = get_parameter_names(model)) :
   attempt to set 'colnames' on an object with less than two dimensions
Calls: %>% ... query_model -> is_a_model -> %in% -> update_model ->
colnames<-_

**This issues does not reproduce locally**

**Comment by macartan** [comment]
Related advice from Ben g

   - Apr '18
   - last reply

   <https://discourse.mc-stan.org/t/initialization-between-2-2-failed-after-100-attempts/3941/5>Apr
   '18


   - 4replies

<https://discourse.mc-stan.org/u/bgoodri>
bgoodri <https://discourse.mc-stan.org/u/bgoodri>
Apr '18
<https://discourse.mc-stan.org/t/initialization-between-2-2-failed-after-100-attempts/3941/2>

First try reducing the interval for the initial values by specifying init_r to
some number less than 2.

**Comment by till-tietz** [comment]
added init_r = 1 to examples. Keeping the censored updating examples in **dontrun** for the upcoming submission.

**Comment by till-tietz** [comment]
```
make_model("X->Y") %>%
update_model(data.frame(X=c(1,1), Y=c(1,1)), censored_types = c("X1Y0")) %>%
query_model(te("X", "Y"), using = "posteriors")
```

runs error free on Linux and Windows

**Comment by macartan** [comment]
great!
