### ISSUE TITLE
stan sampling fails when specifying censored types

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#266]
## minimal working example 

This works: 
```
stanfit <- CausalQueries:::stanmodels$simplexes

model <-  make_model("X->Y") 

data_compact <- 
  collapse_data(
  data.frame(X=c(1,1), Y=c(1,1)), 
  model)

stan_data_0 <- 
  CausalQueries:::prep_stan_data(
    model, data_compact)

updated <- rstan::sampling(stanfit, stan_data_0, refresh = 1)
```
This fails: 
```
stan_data_1 <- 
  CausalQueries:::prep_stan_data(
    model, data_compact,
    censored_types = c("X1Y0", "X0Y0", "X0Y1"))

stan_data_1$parmap

# This blows up
bad <-  rstan::sampling(stanfit, stan_data_1, refresh = 1, iter = 10000)
```

## diagnosis thus far 
This issue is unrelated to normalization with censored types as initially expected

**Comment by integrated-inferences** [comment]
I wonder if the 0s is the multinomial cause problems; what if they were
tinz numbers instead of 0s

**Comment by till-tietz** [comment]
I'll try adding a tiny offset to the multinomial inputs asap today and test.

**Comment by macartan** [comment]
this seemed to work

but I don;t like it:

 // Ensure weights sum to 1
 w = w + 0.000000001;
 w = w / sum(w);

**Comment by till-tietz** [comment]
Great that it works, but yeah, sort of a dodgy fix. Does it cause any numerical stability issues?

**Comment by till-tietz** [comment]
What if we just specify initial values for this case? If the problem are the 0s evaluating to -inf when the mcmc tries to start sampling in log space then that could maybe work right?

**Comment by macartan** [comment]
I'll have to think through that.
The other thing I was thinking abkut is just making the w vector shorter.
So only event probabilities for non 0 events.

Stan team might also have a suggestion since this must be new

**Comment by till-tietz** [comment]
Something vaguely related to this popped up on the Stan forum 5 years ago

 https://discourse.mc-stan.org/t/error-occurred-during-calling-the-sampler-sampling-not-done/6061

The thing that gets me about this though is that everything worked fine until the update. And the changes to the code (except the new array syntax) don't look massive. 

I wonder: did we just always get some sort of floating point voodoo with the old version that prevented things from evaluating exactly to 0?

**Comment by integrated-inferences** [comment]
In the current function even if we specify initial values for w the
likelihood always sends them straight to zero for excluded cases.

In ancient history there was something similar with restrictions on nodal
types: should we force their probability to 0 or prune the whole.model to
exclude them. The latter worked better

**Comment by macartan** [comment]
I have a branch in which w is kept intact and it is pruned only when the
multinomial is run; this has the advantage of letting us preserve the true
w vector (event probabilities without censoring) while still updating with
the censored data

doing tests now and will then fold in but worth a pair of eyes
hopefully tis deals with the Cran bug we had

I noticed also that w is being preserved but not used; it should be used
whenever we do make_data(...posterior_draw)

**Comment by till-tietz** [comment]
Since the fix is merged I'll test the previous CRAN test failure and close the issues.
