### ISSUE TITLE
query_distribution bug

### ISSUE THREAD

**Issue by macartan** [integrated-inferences/CausalQueries#271]
this works

```
make_model("X -> Y") %>% 
  query_distribution(query = "(Y[X=1] > Y[X=0])", using = "priors") %>%
 hist(main = "Prior on Y increasing in X")  
```

But this does not:

```
make_model("X -> Y") %>% 
  query_distribution(query = increasing("X", "Y"), using = "priors") %>%
 hist(main = "Prior on Y increasing in X")  
```

**Comment by till-tietz** [comment]
Thanks for flagging this. Forgot to test with query helpers. 
Will update helpers to work with the new query functionality.

**Comment by till-tietz** [comment]
@macartan querying with query helpers works error free on my end. Have you pulled from master?  The above should not produce a histogram when using the new version as `query_distribution` now produces a DataFrame. 

This should work and produce the same results in both cases: 

```
make_model("X -> Y") %>% 
  query_distribution(query = "(Y[X=1] > Y[X=0])", using = "priors") %>%
  .[[1]] %>%
  hist(main = "Prior on Y increasing in X")  


make_model("X -> Y") %>% 
  query_distribution(query = increasing("X", "Y"), using = "priors") %>%
  .[[1]] %>%
  hist(main = "Prior on Y increasing in X")  
```

**Comment by macartan** [comment]
I just recompiled from master and:

> make_model("X -> Y") %>% +     query_distribution(query = increasing("X", "Y"), using = "priors") %>%+     .[[1]] %>%+     hist(main = "Prior on Y increasing in X")
[image: image.png] Show Traceback
[image: image.png] Rerun with Debug
Error in as.data.frame.default(x[[i]], optional = TRUE,
stringsAsFactors = stringsAsFactors) :
cannot coerce class ‘"statement"’ to a data.frame

or more simply:

> make_model("X -> Y") %>% query_distribution(query = increasing("X", "Y"))
 Show Traceback
 Rerun with Debug
Error in as.data.frame.default(x[[i]], optional = TRUE,
stringsAsFactors = stringsAsFactors) :
cannot coerce class ‘"statement"’ to a data.frame


The problem seems to be here:

```
jobs <- lapply(model_names, function(m) {
    data.frame(
      model_names = m,
      using = unlist(using),
      given = unlist(given),
      queries = unlist(queries),
      case_level = unlist(case_level),
      stringsAsFactors = FALSE)
  }) |>
    dplyr::bind_rows()
```

see:

> data.frame(x = unlist(increasing("A", "B")))Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) :

  cannot coerce class ‘"statement"’ to a data.frame

**Comment by till-tietz** [comment]
I see. Just recompiling from master again on my end to check. The fix can be as simple as looping through queries, detecting statements made with helpers via class and turning them into strings.

**Comment by till-tietz** [comment]
I still can't seem to reproduce the error on my end.

**Comment by macartan** [comment]
interesting we only have it for a single query (or, given I suppose), not
for multiple:

> q <- list("(B[A=1] > B[A=0])", increasing("A", "B"))> data.frame(x = unlist(q))                  x
1 (B[A=1] > B[A=0])
2 (B[A=1] > B[A=0])> q <- list(decreasing("A", "B"), increasing("A",
"B"))> data.frame(x = unlist(q))                  x
1 (B[A=1] < B[A=0])
2 (B[A=1] > B[A=0])

**Comment by macartan** [comment]
strange; this machine is on R 4.2.1, so I am a little behind

**Comment by till-tietz** [comment]
I'll check the exact output of the query helpers. Simply looping through and converting to string might just be good practice for safety/stability regardless of reproducibility of the error

**Comment by macartan** [comment]
OK; note this could be an issue for both queries and givens

**Comment by till-tietz** [comment]
R has some fascinating behavior at times 

```
v <- list("X==1",increasing("X","Y"),"Y==1")
sapply(v, function(i) class(i))

[1] "character" "statement" "character"
```

```
v <- c("X==1",increasing("X","Y"),"Y==1")
sapply(v, function(i) class(i))

             X==1 (Y[X=1] > Y[X=0])              Y==1 
      "character"       "character"       "character" 

```

implicit cast to character internally

**Comment by till-tietz** [comment]
@macartan just pushed an update to master. Does this work on your end?

**Comment by macartan** [comment]
working!

**Comment by till-tietz** [comment]
Fantastic!!! Closing the issue.
