### ISSUE TITLE
wild card

### ISSUE THREAD

**Issue by macartan** [integrated-inferences/CausalQueries#275]
this is in the guide but appears no longer to be valid:

```
make_model("X->Y") |>
  set_restrictions(labels = list(Y = "Y?0"))
```

is it lost entirely or just needs to be reconnected

**Comment by till-tietz** [comment]
May have unintentionally dropped this in the refactor. Should be easy to reconnect wildcard unpacking.

**Comment by till-tietz** [comment]
`set_restrictions` has a logical `wildcard` argument that defaults to `FALSE`. Setting it to `TRUE` enables the unpacking of wildcards when restricting by label. There is; however, still a bug in the way wildcards are applied in `restrict_by_label`. Will fix that issue this weekend.

**Comment by macartan** [comment]
Should it shift to true when there's a ? In the argument?

**Comment by till-tietz** [comment]
I think the cleanest way is to just drop the wildcard argument and always run unpack_wildcard. If no ? are present it just returns the unaltered list of nodal_types. If there is a ? it'll unpack.

**Comment by till-tietz** [comment]
This should now work 

```
make_model("X->Y") |>
  set_restrictions(labels = list(Y = "?0"))
```
