### ISSUE TITLE
update model tests 

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#281]
@macartan 

are we still expecting an error here after your most recent update or is this now possible? 

```
model <- make_model('X->Y')
data_short  <- collapse_data(data_long, model)
expect_error(update_model(model, data_short, refresh = 0))
```

**Comment by macartan** [comment]
good point! this should not now produce an error

**Comment by till-tietz** [comment]
Excellent!!! Updating that test accordingly. We're in very good shape for the update this week. Doing final rounds of testing today. Then all that's left is writing a release note and pushing the big 1.0.0 to CRAN
