### ISSUE TITLE
helpful warning on queries

### ISSUE THREAD

**Issue by macartan** [integrated-inferences/CausalQueries#283]
easy to stumble on =  and ==

get_query_types(model, "Y[X=1]=1") 
**Error in q <- var3 = 1 : could not find function "<-<-"**

get_query_types(model, "Y[X==1]==1") 
**blows up my R**

**Comment by till-tietz** [comment]
I think I figured out a way to warn about wrongly specified strings and fix them in map_query_to_nodal_types and map_query_to_causal_types. It turned out to be a bit trickier than expected but I think it should work. Will push soon.

**Comment by till-tietz** [comment]
implemented `check_query()` (can be found in `helpers.R`) and added it at the top of `map_query_to_nodal_type()` and `map_query_to_causal_type()`. Judging by my tests it can handle arbitrarily complex queries with n levels of nesting. Definitely needs review though to see if it works as intended.

**Comment by till-tietz** [comment]
running 

```
model <- CausalQueries::make_model("X -> Y")
get_query_types(model, "Y[X=1]=1")
```
now produces 

```
Causal types satisfying query's condition(s)  

 query =  Y[X=1]==1 

X0.Y01  X1.Y01
X0.Y11  X1.Y11


 Number of causal types that meet condition(s) =  4
 Total number of causal types in model =  8
Warning message:
In check_query(query) :
  statements to the effect that the realization of a node should equal some value should be specified with `==` not `=`. The query has been changed accordingly: Y[X=1]==1
```

running 

```
model <- CausalQueries::make_model("X -> Y")
get_query_types(model, "Y[X==1]==1")
```

now produces 

```
Causal types satisfying query's condition(s)  

 query =  Y[X=1]==1 

X0.Y01  X1.Y01
X0.Y11  X1.Y11


 Number of causal types that meet condition(s) =  4
 Total number of causal types in model =  8
Warning message:
In check_query(query) :
  do operations should be specified with `=` not `==`. The query has been changed accordingly: Y[X=1]==1
```

**Comment by macartan** [comment]
Looks great

I'd double check no problems with

"Y[X=1]!=1"

“Y[X=1]>=1"

Which are correctly formulated

**Comment by till-tietz** [comment]
Works correctly with the above. I think this issue is good to close.
