### ISSUE TITLE
query from prior distribution bug?

### ISSUE THREAD

**Issue by cristian-nicolescu** [integrated-inferences/CausalQueries#288]
set.seed(9678)
test_model <- make_model("X -> Y") |> set_prior_distribution()
data_test <- test_model |> make_data(n = 5000)
test_model <- update_model(test_model, data = data_test)

post <- query_distribution(test_model, query = "Y[X=1] - Y[X=0]", using = "posteriors")
priors <- query_distribution(test_model, query = "Y[X=1] - Y[X=0]", using = "priors”)

Re-running the last line produces different results each time, not the case for the second-to-last one. Checked with CQ 0.1.0 and this does not happen; last line always gives the same results there. Am I missing something or is this a bug?

**Comment by macartan** [comment]
Hmm. Sounds like the query is not using the existing prior distribution but
is redrawing the prior.  If that's what's happening it's not wrong but it
is inefficient

**Comment by cristian-nicolescu** [comment]
The catch is that when you use queries = list(..) it seems to me that a new prior is drawn for each query, so the rows don't correspond to each other anymore.  Now here I might be wrong but otherwise I cannot explain why I am getting different results than before for our prior analysis.

**Comment by macartan** [comment]
You could test that by having a list with the same query twice.

**Comment by macartan** [comment]
@Till Tietz ***@***.***>  here maybe: line 540

  if((using_i == "priors") && is.null(model[[model_i]]$priors_distribution))
{
      model[[model_i]] <- set_prior_distribution(model[[model_i]], n_draws
= n_draws)
    }

**Comment by till-tietz** [comment]
My sense was the  is.null(model[[model_i]]$priors_distribution` guards against redundant redraws from the prior distribution

**Comment by till-tietz** [comment]
Will check if this is indeed true

**Comment by macartan** [comment]
I had highlighted the s in email but it got killed by git. :(

**Comment by till-tietz** [comment]
Ahhhh... classic bug by dyslexia... my apologies. Will fix and push a patch release to CRAN right away

**Comment by till-tietz** [comment]
fix is on main branch

**Comment by macartan** [comment]
Worth still checking Christians examples though.  This shouldn't have
produced different results in the same call. E.g. with one model and a list
of identical queries

**Comment by till-tietz** [comment]
Checked the example with the new version and it produces the same estimate now

**Comment by till-tietz** [comment]
```
CausalQueries::query_distribution(test_model, query = list("Y[X=1] - Y[X=0]","Y[X=1] - Y[X=0]"), using = "priors") |>
  apply(MARGIN = 2, mean)
```

running this with the previous unfixed version produced the same result. So the bug was entirely down to the misspelling it seems

**Comment by macartan** [comment]
Ok great

**Comment by cristian-nicolescu** [comment]
My results were apparently wrong because I had some cases where I was doing smth like:
query_distribution(model) - query_distribution(model). Now all is clear, thanks for the quick fix!
