### ISSUE TITLE
naming bug

### ISSUE THREAD

**Issue by macartan** [integrated-inferences/CausalQueries#289]
# new batch process breaks naming procedure
```
make_model("X->Y") |>
  query_model(
    list(a = "Y[X=1]",
         b = "Y[X=1]",
         c = "Y[X=1]")
  )
```
query names should be a,b,c
```
> make_model("X->Y") |>
+   query_model(
+     list(a = "Y[X=1]",
+          b = "Y[X=1]",
+          c = "Y[X=1]")
+   )
    model query given      using case_level mean sd cred.low.2.5% cred.high.97.5%
1 model_1     a     - parameters      FALSE  0.5 NA           0.5             0.5
2 model_1     a     - parameters      FALSE  0.5 NA           0.5             0.5
3 model_1     a     - parameters      FALSE  0.5 NA           0.5             0.5
```

**Comment by macartan** [comment]
while we are at it:  new names of credibility intervals cause issue in tex:

cred.low.2.5% cred.high.97.5%

lets revert to

cred.low cred.high

**Comment by till-tietz** [comment]
@macartan 

```
make_model("X->Y") |>
  query_model(
    list(a = "Y[X=1]",
         b = "Y[X=1]",
         c = "Y[X=1]")
  )
```

this returns all query names as "a" because all the queries are the same. The code reassigns query names based on unique query when prepping the output; so as far as query_model is concerned all these queries are just "a". 

Compare to 

```
make_model("X->Y") |>
  query_model(
    list(a = "Y[X=1]",
         b = "Y[X=0]")
  )
```

How do you want to proceed here?

**Comment by till-tietz** [comment]
@macartan 

reverted credible interval names to cred.low and cred.high on `main`

**Comment by macartan** [comment]
the issue is that these are often not the same query
because *really* the query is a combination of query and given
for example the ATE and LATE both have query "Y[X=1] - Y[X=0]"  but one
conditions compilers and the other doesn;t

in the long run the solution might be to have query and given in one
statement; however for now I think  we should retain the names from the
queries list and return it to the output

so here we would keep the list of names (a,b) and reapply these after
estimation

**Comment by till-tietz** [comment]
@macartan I see what you mean.
I'll try to figure out a way to correctly reapply query names. The two challenges here are the expand_grid option and the fact that our helpers are set up to eliminate redundant evaluation.
I think the clean way to do this is to somehow include query names when we make jobs

**Comment by till-tietz** [comment]
@macartan might be an easy fix...we can make jobs with the query names initially and then merge the query statements on based on names prior to passing to helpers

**Comment by till-tietz** [comment]
@macartan query naming issue should be fixed on `main` now

**Comment by macartan** [comment]
Amazing

**Comment by till-tietz** [comment]
I'll hold off on pushing another patch release to CRAN for a few days. They tend not to like very frequent updating.

**Comment by macartan** [comment]
that fine;  lets see if anything else comes up as we finish the paper
by the way the confounds / parmaps branch is ready for review
