### ISSUE TITLE
parmap bug (os dependent?)

### ISSUE THREAD

**Issue by cristian-nicolescu** [integrated-inferences/CausalQueries#293]
test_model <- make_model("X -> M -> Y <- X; M <-> Y") 
test_parmap <- get_parmap(test_model)
 
 Returns on my computer the weird parmap attached:
![Screenshot 2023-11-05 at 12 44 41](https://github.com/integrated-inferences/CausalQueries/assets/67869051/a3136660-0219-41de-974c-b60ce2ceeec5)

So what should be data types are also things like X0M0Y1.1 
Remember thinking when first seeing this that it's got something to do with the model being confounded, but checked this once with Macartan and he was not having the problem, i.e. he only had data types n the column titles. I would mention I'm on macOS, the problem was not there on windows back in the day, but not sure if this is necessarily true.

Would mention that I recall seeing stuff like this happen with the column titles when using code such as:

df <- data.frame(
X = c(..),
Y = c(..),
) 

But I cannot remember the exact circumstances, will see if I can get that happening again. Any ideas? @till-tietz

**Comment by cristian-nicolescu** [comment]
Giving this literally one more second of thought would have made me realize that this obviously happens because a column is defined twice, see: 
df <- data.frame(
         x.0 = c(1, 1),
         x.1 = c(2, 3), 
         x.1 = c(2, 4)
     )
     
     Not the only possibility but seems most likely in this case

**Comment by till-tietz** [comment]
What version are you on?

**Comment by cristian-nicolescu** [comment]
![Screenshot 2023-11-05 at 13 24 22](https://github.com/integrated-inferences/CausalQueries/assets/67869051/2ec19d1f-221c-4939-9887-f2245ecff0ac)
updated cq 2 weeks ago I think. But I have had this issue in all versions of the package!

**Comment by till-tietz** [comment]
This is very strange. Looks like we'll have to check the mac OS  binary builds since this issue doesn't seem to reproduce on 1.0.1 for windows + Linux

**Comment by cristian-nicolescu** [comment]
Taking the OS dependent stuff back: this is happening on the windows PCs at WZB as well, will send version of cq there soon

**Comment by till-tietz** [comment]
@cristian-nicolescu any update on the version that produces the bug? There have been recent updates to `parmap` that are now on main. Would be curious if those resolve the issue

**Comment by cristian-nicolescu** [comment]
Very sorry for the late reply: On mac both cran and dev the (newest) versions still have the bug, will update on windows asap

**Comment by till-tietz** [comment]
Bug resolved as of 1.1.1
