### ISSUE TITLE
simplifying set_restrictions

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#302]
@macartan  currently updates to `P`  and `causal_types` after setting restrictions are somewhat convoluted. 
Would it perhaps be cleaner to set restrictions on nodal types and then use existing helpers to build out other data structures from the restricted types again?

**Comment by macartan** [comment]
Maybe! My instinct, perhaps wrongly, is that it is faster to delete rows
and columns in P than to recreate it; but I might not be right on that.
Also, we always have to take account of the confounding structure so it's
not just nodal types, but the rows of parameters_df; reason is that we
restrict parameters not nodal types
