### ISSUE TITLE
Hyphens in statements

### ISSUE THREAD

**Issue by lilymedina** [integrated-inferences/CausalQueries#306]
While writing tests for the `make_model` function, I noticed that the following code doesn't trigger the error that checks hyphens in the node names

```
make_model("institutions -> political-inequality")

Statement: 
[1] "institutions -> political-inequality"

DAG: 
        parent  children
1 institutions political

...
```

While this does:

```
make_model("political-inequality <- institutions")

Error in make_model("political-inequality <- institutions") : 
  No hyphens in varnames please; try dots?
```

The difference in behavior is due to how daggitty parses hyphens in names after the "->" compared to before; when node names after "->" include hyphens, the hyphen is removed along with any characters that come after it.

I don't know how much there is to do on our end, but I just wanted to flag it.

**Comment by till-tietz** [comment]
Thanks for flagging @lilymedina ... will fix
