### ISSUE TITLE
Improve S3 methods 

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#316]
S3 methods require standardization + improvement:  

1. It seems that for output_type == "logical" there is a cat("\n") missing in `getS3method("print", "summary.causal_types")`. This implies that after printing the prompt is *not* at the beginning of a new line.

2. Some print() methods of an object just print the summary object obtained using summary(). This seems not desirable, but a briefer output should be provided using print() than summary().
```
getS3method("print", "causal_model") function (x, ...) { print(summary(x))
invisible(x) }
```

3. The range of methods provided for example for "causal_model" also raises the question if more methods could be provided: e.g. to avoid exposing the internal structure as done when accessing elements as in model$posterior_distribution
```
methods(class = "causal_model") [1] plot print summary
```

**Comment by wzb-ipi** [comment]
for query_model I was thinking print output something like this:

  print.summary.query_model <- function(x,  digits = 2, ...) {

    x |> mutate(query = ifelse(given == "-", query, paste(query, "¦", given))) |>
      select(query, using, level = case_level, mean, sd) |>
      mutate(level = ifelse(level, "pop", "case")) |>
      knitr::kable(digits = digits, na = "") |>
      cat(sep = "\n")
  }

**Comment by till-tietz** [comment]
@macartan what are your thoughts on dropping summary methods for map_query_to_nodal_types, map_query_to_causal_types and make_parameter_matrix and keeping only a print method?

**Comment by gerasy1987** [comment]
I can take up the `causal_model` print method since I have been working on that anyway. Would something like this work for the output there?

```r
model <- make_model('X->Y')
model

> Statement: 
> [1] "X->Y"
> 
> DAG: 
>   parent children
> 1      X        Y
```

**Comment by till-tietz** [comment]
@gerasy1987 existing print and summary methods are already updated as per reviewer comments. Just have the changes living on the S3_improvement branch for now

**Comment by macartan** [comment]
ok -- sounds like this is in hand, but a note that in practice when I type

model

I am most interested normally in the summary of restrictions; I realize the
idea is that print is shorter than summary but would at least like to
include that, so, e.g:

make_model("X -> Y") |> set_restrictions("X[]==1")

Statement:

[1] "X -> Y"

DAG:

  parent children

1      X        Y



Number of types by node

X Y

1 4

Number of unit types:  4

**Comment by till-tietz** [comment]
@macartan the output you outlined above is implemented on the s3_improvements branch

**Comment by till-tietz** [comment]
all S3 methods are implemented
