### ISSUE TITLE
tests for summary and print methods are broken

### ISSUE THREAD

**Issue by gerasy1987** [integrated-inferences/CausalQueries#325]
It seems that tests are broken for 

- `summary.causal_types`
- `print.summary.causal_types`
- `summary.parameter_matrix`

since these functions were removed from main branch. Any reason to keep those tests?

**Comment by till-tietz** [comment]
@gerasy1987 thanks for pointing this out. No reason to keep them since summary methods for these objects are deprecated now. Will remove the tests.
