### ISSUE TITLE
fix adjust_edge

### ISSUE THREAD

**Issue by till-tietz** [integrated-inferences/CausalQueries#353]
edges overlap with nodes when edge slope is 0 or inf

**Comment by till-tietz** [comment]
# fixed
- node/edge overlap issue when edge slope is 0 or inf 

# open 
- edge adjustment for confounding edges does not account for curvature 

# potential fixes 
- add column that decides direction + degree of curvature based on overlap with other nodes / edges 
- adjust start/endpoints of confounding edges to account for curvature

**Comment by till-tietz** [comment]
### potential solution: 

for confounding edge place a control point that ensures no overlap between edges. calculate adjustment of start and end points w.r.t the control point. Construct spline curve with start, end and control point `splinefun(curve$x, curve$y, "natural")` plot curve with `geom_function`

**Comment by macartan** [comment]
Hi TIll --

think that's worth a shot; in the meantime I implemented:

  p <-
    ggplot() +
    geom_curve(
      data = dag_plot[dag_plot$direction == "<->" & !is.na(dag_plot$direction
== "<->"), ],
      aes(x = x, y = y, xend = xend, yend = yend),
      curvature = 0.4,
      linetype = "dotted"
    ) +
    geom_point(
      data = dplyr::distinct(dag_plot, name, .keep_all = TRUE),
      aes(x = x, y = y),
      size = 1.3 * nodesize, color = "white", shape = shape
    ) +
    geom_point(
      data = dplyr::distinct(dag_plot, name, .keep_all = TRUE),
      aes(x = x, y = y),
      size = nodesize, color = nodecol, shape = shape
    ) +

which does dotted lines to the center of the text but appearing to start
outside of the node circle

I also added a label argument so you can do e.g.

#' make_model('X -> K -> Y; X <-> Y') |> plot_model(labels = c("A long
label for X", "This", "That"))

**Comment by macartan** [comment]
example of curve going outside plot boundaries:

make_model('X -> K -> Y; X <-> Y') |> plot_model(x_coord = c(2, 0.8, 0),
y_coord = c(3.5, 0, 4))

this can be fixed manually with +ylim()

but surprising it can happen

**Comment by macartan** [comment]
Thanks Till;  if your method is working and lighter I am happy with that
too; I think best to keep it simple rather than options here

* currently all tests passing; I redid tests and help files also
