### ISSUE TITLE
dots in names cause problems in models with confounding

### ISSUE THREAD

**Issue by wzb-ipi** [integrated-inferences/CausalQueries#365]
> x <- make_model("X -> Y.1 <-> X")
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

**Comment by till-tietz** [comment]
@macartan is this addressed yet?

**Comment by macartan** [comment]
I don’t think so

A. Simplest might be to disallow names with dots when there is confounding

B. Otherwise we’d need to change names of conditional parameters which also
use .; perhaps to ..


I’d suggest A. This is a rare thing
