### ISSUE TITLE
`make_data()` has default `verbose=TRUE`

### ISSUE THREAD

**Issue by gerasy1987** [integrated-inferences/CausalQueries#369]
This default makes it harder to save created data without producing a printout. Suggest we switch to `verbose=FALSE` by default.

**Comment by till-tietz** [comment]
@gerasy1987 will change to `verbose=FALSE`

**Comment by macartan** [comment]
May have to check tests also then …

**Comment by till-tietz** [comment]
changed default in `make_data()` to `verbose = FALSE`. Tests passing. Closing Issue.
